# Generated by Django 4.0.1 on 2022-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='age',
            field=models.IntegerField(),
        ),
    ]
